services:
  task-db:
    image: postgres:17
    container_name: task-db
    hostname: task-db
    ports:
      - ${TASK_DB_HOST_PORT}:${TASK_DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${TASK_DB_USER}
      POSTGRES_PASSWORD: ${TASK_DB_PASSWORD}
      POSTGRES_DB: ${TASK_DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data