spring:
   application: 
      name: gateway
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8181/realms/task-scheduler-realm
springdoc:
   swagger-ui:
      path: /swagger-ui.html
      urls: 
         - name: Task Service
           url: /aggregate/task-service/v3/api-docs
   api-docs: 
      path: /api-docs
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

task:
   service:
      url: http://localhost:8080

server: 
   port: 9000